name: Preview Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g firebase-tools
      - run: firebase hosting:channel:deploy preview --token "${{ secrets.FIREBASE_TOKEN }}"
